package frontend;

public enum TokenType {
PUNCTUATION, SYMBOL, NUMBER,
OPEN_LIST, CLOSE_LIST,
// RESERVED WORDS "_" instead of -
// _BANG == !
// _STAR == *
AND, BEGIN, BEGIN0, BREAK_VAR, CASE, COND, CYCLE, DEFINE, 
DELAY, DELAY_LIST_CONS, DO, ELSE, EXTEND_SYNTAX, FOR, 
FREEZE, IF, LAMBDA, LET, LETREC, LET_STAR, MACRO, OBJECT_MAKER, 
OR, QUOTE, REPEAT, SAFE_LETREC, SET_BANG, STREAM_CONS, 
VARIABLE_CASE, WHILE, WRAP,
// #t #f
TRUE, FALSE
}
